name: Docker Image CI

on:
  push: # push 时触发ci
    branches: [master] # 作用于main分支
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 拉取main分支代码
      - name: Checkout
        uses: actions/checkout@v2

      # 制作docker镜像并推送到阿里云容器镜像服务
      - name: build and push docker image
        run: |
          echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login xxx.com --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin
          docker image build -t blog:latest .
          docker tag blog xxx.com/xxx/blog:latest
          docker push xxx.com/xxx/blog:latest
          docker logout

       # 创建文件夹
      - name: Copy docker-compose file to server
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir -p /app/blog
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
          
       # 复制docker-compose.yml和nginx到服务器
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "docker-compose.yml"
          target: "/app/blog"
      # 登录远程服务器，使用docker-compose启动服务
      - name: ssh remote deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /app/blog
            echo -e "1.docker login start==>"
            echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login xxx.com --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin
            
            echo -e "2.delete old images and restart containers==>"
            docker compose down --rmi all
            docker compose up -d
            
            echo -e "3.docker logout==>"
            docker logout
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}

